name: test-disk-space

on:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: OpenWrt-repository
        required: true
        type: choice
        default: https://github.com/openwrt/openwrt.git
        options:
        - https://github.com/openwrt/openwrt.git
        - https://github.com/coolsnowwolf/lede.git
        - https://github.com/Lienol/openwrt.git
        - https://github.com/immortalwrt/immortalwrt.git
      REPO_BRANCH:
        description: Enter the branch of the OpenWrt
        required: true
        type: string
        default: main
      CONFIG_FILE:
        description: Enter your config file
        required: true
        type: string
        default: ax6s
      UPLOAD_RELEASE:
        description: UPLOAD_RELEASE
        required: true
        type: string
        default: false

env:
  REPO_URL: ${{ inputs.REPO_URL }}
  REPO_BRANCH: ${{ inputs.REPO_BRANCH }}
  CONFIG_FILE: config/${{ inputs.CONFIG_FILE }}.config
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: .github/FIRST.sh
  DIY_P2_SH: .github/SECOND.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: ${{ inputs.UPLOAD_RELEASE }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Optimize Disk Space
      uses: hugoalh/disk-space-optimizer-ghaction@main
      with:
        operate_sudo: "True"
        general_include: ".+"
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: Freeing up disk space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 64
        swap-size-mb: 64
        temp-reserve-mb: 64
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        
    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
